const fs = require('fs');
const path = require('path');

// Simple favicon.ico generator using a base64 encoded 16x16 icon
// This creates a simple purple circle with nodes representing the intent market

const faviconBase64 = `AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEFBQQZFRUUeT09PPVhYWFVeXl5jYmJiY11dXVVUVFQ9SkpKHkBAQAYAAAAAAAAAAAAAAAAAAAAASEhIHl1dXX9ubm7Xenp64oKCgv+Ghob/hoaG/4KCgv96enridnZ2v2ZmZn9PT08eAAAAAAAAAAAAAAAAVFVVPXNzc796enr/gYGB/4eHh/+Li4v/jIyM/4uLi/+Hh4f/gYGB/3p6ev9wcHC/VFVVPQAAAAAAAAAAbW1tVX5+fOKHh4f/jY2N/5GRkf+UlJT/lZWV/5SUlP+RkZH/jY2N/4eHh/9+fn7ibW1tVQAAAAAAAAAAe3t7Y4aGhv+NjY3/kpKS/5aWlv+ZmZn/mpqa/5mZmf+Wlpb/kpKS/42Njf+Ghob/e3t7YwAAAAAAAAAAgoKCY4uLi/+RkZH/lpaW/5mZmf+cnJz/nZ2d/5ycnP+ZmZn/lpaW/5GRkf+Li4v/goKCYwAAAAAAAAAAfX19VYeHh+KOjo7/k5OT/5aWlv+ZmZn/mpqa/5mZmf+Wlpb/k5OT/46Ojv+Hh4fifX19VQAAAAAAAAAAT09PPXNzc795eXn/gICB/4aGhv+Kiov/i4uL/4qKi/+Ghob/gICA/3l5ef9wcHC/T09PPQAAAAAAAAAARERERF1dXX9tbW3XeHh44oCAhP+EhIT/hISE/4CAhP94eHjidXV1v2VlZX9KSkoaAAAAAAAAAAAAAAAAAAAAQEBABkVFRR5PT089WFhYVV5eXmNiYmJjXV1dVVRUVD1KSkoeQEBABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=`;

// Write the favicon.ico file
const buffer = Buffer.from(faviconBase64, 'base64');
fs.writeFileSync(path.join(__dirname, '../public/favicon.ico'), buffer);

console.log('✅ Favicon generated successfully!');
console.log('   The icon represents the intent market with a central user node connected to multiple agent nodes.');